String sanitizeKeySegment(String input) {
  final cleaned = input
      .trim()
      .replaceAll(RegExp(r'[^A-Za-z0-9._-]'), '_')
      .replaceAll(RegExp(r'_+'), '_')
      .replaceAll(RegExp(r'^_+|_+$'), '');
  return cleaned;
}

String buildProjectKey({
  required String projectName,
  required String substructureElement,
  required String pileNumber,
}) {
  final parts = [
    sanitizeKeySegment(projectName),
    sanitizeKeySegment(substructureElement),
    sanitizeKeySegment(pileNumber),
  ].where((part) => part.isNotEmpty).toList();

  if (parts.isEmpty) {
    return 'project';
  }
  return parts.join('_');
}

String deriveProjectKeyFromFileName(String fileName) {
  final dotIndex = fileName.lastIndexOf('.');
  var base = dotIndex > 0 ? fileName.substring(0, dotIndex) : fileName;

  // Remove duplicate suffix generated by _nextAvailableFilePath, e.g. _(1)
  base = base.replaceFirst(RegExp(r'_\(\d+\)$'), '');

  // Remove timestamp suffix used by exports: _MMddyy_HHmm
  base = base.replaceFirst(RegExp(r'_\d{6}_\d{4}$'), '');

  final sanitized = sanitizeKeySegment(base);
  return sanitized.isEmpty ? 'project' : sanitized;
}

String humanizeProjectKey(String projectKey) {
  final text = projectKey.replaceAll('_', ' ').trim();
  if (text.isEmpty) {
    return 'Project';
  }
  return text;
}
